### ISSUE TITLE
PermissionError: [WinError 5] Access is denied on daemon\server.py", line 1112, in start_service

### ISSUE THREAD

**Issue by AtomicInternet2** [madMAx43v3r/chia-gigahorse#107]
Used to run great, now stopped. I'm sure some Windows security update killed it. Can't find any trace of "WinError 5 gigahorse" so I'm starting to think it's just me. Let me know if you see something I haven't tried yet that I should.

- **System:** Windows 11 Pro
- **Chia-Gigahorse:** 1.8.0.giga10 (latest)
- Added chia.exe to Windows firewall (public and private)
- Gave "Everyone" full permission to ~/.chia
- Gave "Everyone" full permission to ~/.chia_keys
- Gave "Everyone" full permission to program files (C:\chia-gigahorse-farmer)
- Ran os.chmod(<<above directories>>, 0o777) for good measure in Python

Below is the log that spits out after immediately giving up. Any tips would be appreciated.

`2023-05-05T17:18:58.733 daemon chia.daemon.server         : ERROR    problem starting chia_harvester
Traceback (most recent call last):
  File "C:\CHIA-G~1\chia\daemon\server.py", line 1112, in start_service
  File "C:\CHIA-G~1\chia\daemon\server.py", line 1287, in launch_service
  File "C:\CHIA-G~1\subprocess.py", line 971, in __init__
  File "C:\CHIA-G~1\subprocess.py", line 1440, in _execute_child
PermissionError: [WinError 5] Access is denied
2023-05-05T17:18:58.733 daemon chia.daemon.server         : ERROR    problem starting chia_timelord_launcher
Traceback (most recent call last):
  File "C:\CHIA-G~1\chia\daemon\server.py", line 1112, in start_service
  File "C:\CHIA-G~1\chia\daemon\server.py", line 1287, in launch_service
  File "C:\CHIA-G~1\subprocess.py", line 971, in __init__
  File "C:\CHIA-G~1\subprocess.py", line 1440, in _execute_child
PermissionError: [WinError 5] Access is denied
2023-05-05T17:18:58.749 daemon chia.daemon.server         : ERROR    problem starting chia_timelord
Traceback (most recent call last):
  File "C:\CHIA-G~1\chia\daemon\server.py", line 1112, in start_service
  File "C:\CHIA-G~1\chia\daemon\server.py", line 1287, in launch_service
  File "C:\CHIA-G~1\subprocess.py", line 971, in __init__
  File "C:\CHIA-G~1\subprocess.py", line 1440, in _execute_child
PermissionError: [WinError 5] Access is denied
2023-05-05T17:18:58.749 daemon chia.daemon.server         : ERROR    problem starting chia_farmer
Traceback (most recent call last):
  File "C:\CHIA-G~1\chia\daemon\server.py", line 1112, in start_service
  File "C:\CHIA-G~1\chia\daemon\server.py", line 1287, in launch_service
  File "C:\CHIA-G~1\subprocess.py", line 971, in __init__
  File "C:\CHIA-G~1\subprocess.py", line 1440, in _execute_child
PermissionError: [WinError 5] Access is denied
2023-05-05T17:18:58.749 daemon chia.daemon.server         : ERROR    problem starting chia_full_node
Traceback (most recent call last):
  File "C:\CHIA-G~1\chia\daemon\server.py", line 1112, in start_service
  File "C:\CHIA-G~1\chia\daemon\server.py", line 1287, in launch_service
  File "C:\CHIA-G~1\subprocess.py", line 971, in __init__
  File "C:\CHIA-G~1\subprocess.py", line 1440, in _execute_child
PermissionError: [WinError 5] Access is denied
2023-05-05T17:18:58.749 daemon chia.daemon.server         : ERROR    problem starting chia_wallet
Traceback (most recent call last):
  File "C:\CHIA-G~1\chia\daemon\server.py", line 1112, in start_service
  File "C:\CHIA-G~1\chia\daemon\server.py", line 1287, in launch_service
  File "C:\CHIA-G~1\subprocess.py", line 971, in __init__
  File "C:\CHIA-G~1\subprocess.py", line 1440, in _execute_child
PermissionError: [WinError 5] Access is denied
2023-05-05T17:18:58.749 daemon chia.daemon.server         : ERROR    problem starting chia_data_layer
Traceback (most recent call last):
  File "C:\CHIA-G~1\chia\daemon\server.py", line 1112, in start_service
  File "C:\CHIA-G~1\chia\daemon\server.py", line 1287, in launch_service
  File "C:\CHIA-G~1\subprocess.py", line 971, in __init__
  File "C:\CHIA-G~1\subprocess.py", line 1440, in _execute_child
PermissionError: [WinError 5] Access is denied
2023-05-05T17:18:58.760 daemon chia.daemon.server         : ERROR    problem starting chia_data_layer_http
Traceback (most recent call last):
  File "C:\CHIA-G~1\chia\daemon\server.py", line 1112, in start_service
  File "C:\CHIA-G~1\chia\daemon\server.py", line 1287, in launch_service
  File "C:\CHIA-G~1\subprocess.py", line 971, in __init__
  File "C:\CHIA-G~1\subprocess.py", line 1440, in _execute_child
PermissionError: [WinError 5] Access is denied
`

**Comment by AtomicInternet2** [comment]
So I actually found the "start_service permission error" in Google after some more digging, and you need to give the "NETWORK_SERVICE" user permission to the source files (C:\chia-gigahorse-farmer in my case).  It's up and running now, no idea why it was fine without those permissions before.  I'll leave this in case I'm not the only one.

**Comment by AtomicInternet2** [comment]
And now I've rebooted and permissions all denied again.  I've gone through and given every single account in my system full access to those 3 directories, rebooted several times, and still no luck.

**Comment by madMAx43v3r** [comment]
Maybe some restrictive security settings in your windows?

**Comment by AtomicInternet2** [comment]
I'm not sure if you can add some error catching on \daemon\server.py, line 1112, or if that's even your code, but if it could spit out what user is being denied that would be very helpful if this becomes a problem for more than me.  My issue is intermittent, so whatever is causing it is my machine.  I've also got the SCEP enrollment issue here that likes to lock out my remote desktop and other fun things, so it could just be that acting up: https://community.amd.com/t5/processors/scep-certificate-enrollment-initialization-errors-are-back-again/td-p/546630/page/3

Either way I'm up and running for now, appreciate the response.  Hopefully this is helpful for more than just me if someone else runs into WinError 5.  Adding the service accounts at least give me a 50/50 chance of not getting the error now.

**Comment by madMAx43v3r** [comment]
Nice setup, I've seen this before somewhere

**Comment by madMAx43v3r** [comment]
The error happens on the call `subprocess.Popen`, which starts another process, like farmer or harvester.

**Comment by madMAx43v3r** [comment]
Maybe no permissions to execute `chia.exe` ?

**Comment by AtomicInternet2** [comment]
These are the permissions for all 3 folders that seemed to fix the issue.  I don't know why the new processes doesn't inherit from the launching user, but this seemed to fix it (for now).  Hopefully I'm the only one who has the issue lol.
![image](https://user-images.githubusercontent.com/132714132/236642408-6e59687c-c804-428d-b0da-8853cb4cc64b.png)

**Comment by madMAx43v3r** [comment]
how do you start gigahorse in the first place?

**Comment by madMAx43v3r** [comment]
`all parent folders should have +x permission`

**Comment by AtomicInternet2** [comment]
All folders have full rights for all service accounts.  I run the following as admin / non-admin with same error.

I finally just keep running "chia.exe start all" in an infinite loop until I eventually get a "success" and quit.  I have no idea why I have this issue.

`:loop
timeout /t 1 >nul
chia.exe start all | find "success"    
if errorlevel 1 goto :loop
echo successful.`

**Comment by madMAx43v3r** [comment]
Should use `chia.exe start farmer`
