### ISSUE TITLE
1.8.0.giga10 Gigahorse Node / Farmer Losing Network Sync

### ISSUE THREAD

**Issue by darkenbula** [madMAx43v3r/chia-gigahorse#108]
I have recently switched from the official client to Gigahose 1.7 and now 1.8. Since then i have been having problems with the node losing network sync.  Initially i had UPnP enabled but have disabled it now, port 8444 is forwarded and i can see plenty of traffic through my firewall to this port 

Intel(R) Xeon(R) CPU E5-2620 v4
256GB Ram
Nvidia 3060ti - plotting
Quadro M2000

When i look back through the logs the only thing i see which might be related it this,.

2023-05-07T01:06:36.051 wallet chia.wallet.wallet_state_manager: ERROR    set_sync_mode failed - range: 3623376-3623542, seconds: 0.3210752010345459
Traceback (most recent call last):
  File "C:\Users\HPZ640\Desktop\CHIA-G~1\.\chia\wallet\wallet_state_manager.py", line 524, in set_sync_mode
  File "C:\Users\HPZ640\Desktop\CHIA-G~1\.\chia\wallet\wallet_node.py", line 1120, in long_sync_from_untrusted
  File "C:\Users\HPZ640\Desktop\CHIA-G~1\.\chia\wallet\wallet_node.py", line 751, in long_sync
  File "C:\Users\HPZ640\Desktop\CHIA-G~1\.\chia\wallet\util\wallet_sync_utils.py", line 79, in subscribe_to_phs

**Comment by madMAx43v3r** [comment]
That error is just for the wallet, not the node...

**Comment by madMAx43v3r** [comment]
Maybe try a fresh config, and delete `db/peers.dat`

**Comment by madMAx43v3r** [comment]
Can you provide logs when it loses the sync?

**Comment by darkenbula** [comment]
> Maybe try a fresh config, and delete `db/peers.dat`

This seems to  have fixed mine. Been going for a little over 48 hours now which is the longest it's been so far. Connected to max number of peers etc
