### ISSUE TITLE
 Failed to load cache: DiskProver: Invalid version., Traceback (most recent call last)

### ISSUE THREAD

**Issue by abcl52kdk** [madMAx43v3r/chia-gigahorse#144]
chia plots check -g /mnt/b/farm-gigahorse/plot-k32-c7-2023-05-24-20-29-a.plot
2023-06-05T22:44:11.057  chia.plotting.check_plots        : INFO     Loading plots in config.yaml using plot_manager loading code (parallel read: True)

2023-06-05T22:44:11.327  chia.plotting.cache              : INFO     Loaded 1213445 bytes of cached data
2023-06-05T22:44:11.567  chia.plotting.cache              : ERROR    Failed to load cache: DiskProver: Invalid version., Traceback (most recent call last):
  File "chia/plotting/cache.py", line 143, in load
ValueError: DiskProver: Invalid version.

2023-06-05T22:44:11.655  chia.plotting.check_plots        : INFO     event: started, loaded 0 plots, 147 remaining
2023-06-05T22:44:11.656  chia.plotting.manager            : INFO     Only loading plots that contain "/mnt/b/farm-gigahorse/plot-k32-c7-2023-05-24-20-29-a.plot" in the file or directory name
2023-06-05T22:44:11.667  chia.plotting.manager            : ERROR    Failed to open file /mnt/b/farm-gigahorse/plot-k32-c7-2023-05-24-20-29-a.plot. Invalid plot file format Traceback (most recent call last):
  File "chia/plotting/manager.py", line 274, in process_file
ValueError: Invalid plot file format

2023-06-05T22:44:11.669  chia.plotting.check_plots        : INFO     event: batch_processed, loaded 0 plots, 0 remaining
2023-06-05T22:44:11.669  chia.plotting.check_plots        : INFO     event: done, loaded 0 plots, 0 remaining
2023-06-05T22:44:12.670  chia.plotting.check_plots        : INFO     
2023-06-05T22:44:12.671  chia.plotting.check_plots        : INFO     
2023-06-05T22:44:12.671  chia.plotting.check_plots        : INFO     Summary
2023-06-05T22:44:12.672  chia.plotting.check_plots        : INFO     Found 0 valid plots, total size 0.00000 TiB
2023-06-05T22:44:12.672  chia.plotting.check_plots        : WARNING  1 invalid plots found:
2023-06-05T22:44:12.672  chia.plotting.check_plots        : WARNING      1 unopenable plots:
2023-06-05T22:44:12.673  chia.plotting.check_plots        : WARNING  /mnt/b/farm-gigahorse/plot-k32-c7-2023-05-24-20-29-a.plot

**Comment by liucaiyang** [comment]
my system is  ubuntu 20 and chia version is chia-blockchain_1.8.0_amd64.deb and gigahorse farm version is chia-gigahorse-farmer-1.8.1.giga13-x86_64.tar.gz

**Comment by abcl52kdk** [comment]
Excuse me, what is the problem? After restarting the computer, all plot files are invalid, and all files are valid before restarting.

**Comment by abcl52kdk** [comment]
Excuse me, what is the problem? After restarting the computer, all plot files are invalid, and all files are valid before restarting.

**Comment by madMAx43v3r** [comment]
make sure to use the gigahorse version, it looks like it's using official version
