### ISSUE TITLE
Getting software error in harvester code.

### ISSUE THREAD

**Issue by usao-az** [madMAx43v3r/chia-gigahorse#164]
```
2023-07-03T20:18:38.138 harvester harvester_server        : ERROR    Exception: Given G1 non-infinity element must start with 0b10 <class 'ValueError'>, closing connection PeerInfo(_ip=IPv4Address('192.168.0.90'), _port=8447). Traceback (most recent call last):
  File "/home/chia/chia-blockchain/chia/server/ws_connection.py", line 388, in _api_call
    coroutine = f(full_message.data, self)
  File "/home/chia/chia-blockchain/chia/util/api_decorators.py", line 63, in wrapper
    arg = message_class.from_bytes(original)
  File "/home/chia/chia-blockchain/chia/util/streamable.py", line 648, in from_bytes
    parsed = cls.parse(f)
  File "/home/chia/chia-blockchain/chia/util/streamable.py", line 635, in parse
    object.__setattr__(obj, field.name, field.parse_function(f))
  File "/home/chia/chia-blockchain/chia/util/streamable.py", line 443, in <lambda>
    return lambda f: parse_list(f, parse_inner_type_f)
  File "/home/chia/chia-blockchain/chia/util/streamable.py", line 394, in parse_list
    full_list.append(parse_inner_type_f(f))
  File "/home/chia/chia-blockchain/chia/util/streamable.py", line 450, in <lambda>
    return lambda f: parse_size_hints(f, f_type, bytes_to_read, unchecked=True)
  File "/home/chia/chia-blockchain/chia/util/streamable.py", line 409, in parse_size_hints
    return f_type.from_bytes_unchecked(bytes_read)
ValueError: Given G1 non-infinity element must start with 0b10

```

**Comment by madMAx43v3r** [comment]
You're mixing official chia with gigahorse, cannot do that.
