### ISSUE TITLE
Farm size 0 TB Windows 11

### ISSUE THREAD

**Issue by Dakes12** [madMAx43v3r/chia-gigahorse#184]
Hello,

I am willing to replot all of my hhd's (1.23 PiB) and i started just with few, trying to understand how is working.
Actually, i am facing the following problem on all pools that i have tried to farm gigahorse compressed plots.
On every pool that i tried to farm, gigahorse farmer says that i am farmin on pool, but when i check my farm status shows 0 TB.

farm summary:
Farming status: Farming
Total chia farmed: 0.0
User transaction fees: 0.0
Block rewards: 0.0
Last height farmed: 0
Local Harvester
   525 plots of size: 36.555 TiB
Plot count for all harvesters: 525
Total size of plots: 36.555 TiB
Estimated network space: 26.291 EiB
Expected time to win: 5 months

plotnft show:
Current state: FARMING_TO_POOL
Current state from block height: 4049696
Launcher ID: ...
Target address (not for plotting): ...
Number of plots: 524
Owner public key: ...
Pool contract address (use ONLY for plotting - do not send money to this address): ...
Current pool URL: https://xch.spacefarmers.io
Current difficulty: 1
Points balance: 0
Points found (24h): 0
Percent Successful Points (24h): 0.00%
Payout instructions (pool will pay to this address): ...
Relative lock height: 100 blocks

I don't know how to make it working.. 
P.S: i am not a pro, using cmd and linux. Maybe you can help me by explaining in common terms :).

Also, i am facing problems in using Remote Compute. Maybe someone can explain me how i can make it working with 2 main farmers (gpu) and 4 harvesters.

Thank you in advance!

**Comment by Dakes12** [comment]
Log:
2023-08-06T20:54:29.208 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2023-08-06T20:54:29.208 wallet wallet_server              : WARNING  Banning 150.230.120.82 for 120 seconds
2023-08-06T20:54:29.208 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2023-08-06T20:54:29.208 wallet wallet_server              : WARNING  Banning 171.231.23.103 for 120 seconds
2023-08-06T20:54:44.965 wallet chia.wallet.wallet_node    : ERROR    Error syncing to PeerInfo(_ip=IPv4Address('37.235.174.43'), _port=8444)
Traceback (most recent call last):
  File "C:\Users\dakes\Desktop\CHIA-G~1.2-W\CHIA-G~1\chia\wallet\wallet_node.py", line 1135, in new_peak_from_untrusted
  File "C:\Users\dakes\Desktop\CHIA-G~1.2-W\CHIA-G~1\chia\wallet\wallet_node.py", line 1144, in long_sync_from_untrusted
  File "C:\Users\dakes\Desktop\CHIA-G~1.2-W\CHIA-G~1\chia\wallet\wallet_node.py", line 1263, in fetch_and_update_weight_proof
Exception: weight proof response was none
2023-08-06T20:54:57.408 harvester chia.harvester.harvester: ERROR    Error using prover object connect() failed with: timeout (> 2000 ms)
2023-08-06T20:54:57.408 harvester chia.harvester.harvester: ERROR    Error using prover object connect() failed with: timeout (> 2000 ms)
2023-08-06T20:54:57.423 harvester chia.harvester.harvester: ERROR    File: E:\plot-k32-c8-2023-08-02-08-54-4b0ef1c6ef8b3fcfc5e4403868ddae1bc8b4615efb0136f7c2787a950527a3a0.plot Plot ID: 4b0ef1c6ef8b3fcfc5e4403868ddae1bc8b4615efb0136f7c2787a950527a3a0, challenge: 089b35795aa9eac8908e1e0a4cb10a941e27570fbfc5edc3212a1e75be2fb229, plot_info: PlotInfo(prover=<chiapos.DiskProver object at 0x000001381644C4B0>, pool_public_key=None, pool_contract_puzzle_hash=<bytes32: 5316242367eb37f1ab1e982dfc26297a6392962cc0e423304881887cf6362447>, plot_public_key=<G1Element 97a133ddfd383ebf4b8894a99b3a51303ef532ccaa4c794fd1558dbc69324cf7601935401b55270249d6640ff9935f4b>, file_size=76527354464, time_modified=1690955880.104747)
2023-08-06T20:54:57.423 harvester chia.harvester.harvester: ERROR    File: E:\plot-k32-c8-2023-08-02-07-58-b80fc0fc7cca2930d310855139c363bf73173b67a5e2803e2f95b7f0768f58a8.plot Plot ID: b80fc0fc7cca2930d310855139c363bf73173b67a5e2803e2f95b7f0768f58a8, challenge: fe88a690e5975ccfdf9655c0a191b0b5164bd9e8431cc799bb6c711e77e18662, plot_info: PlotInfo(prover=<chiapos.DiskProver object at 0x000001381644C4F0>, pool_public_key=None, pool_contract_puzzle_hash=<bytes32: 5316242367eb37f1ab1e982dfc26297a6392962cc0e423304881887cf6362447>, plot_public_key=<G1Element a07f42ed5a065d47406f4623d7af321209263666f8912fde043bbd2c64eb9ff50870a8dc2d023e2e671b50a1a6279a81>, file_size=76527625712, time_modified=1690952511.1934779)
2023-08-06T20:55:24.154 harvester chia.harvester.harvester: ERROR    Error using prover object connect() failed with: timeout (> 2000 ms)
2023-08-06T20:55:24.170 harvester chia.harvester.harvester: ERROR    File: F:\plot-k32-c8-2023-08-03-01-31-53e6b00bcf389abd2ac4ffa675fb19eb4e1e5bdbd3f8bed9cda4b6c867258dc6.plot Plot ID: 53e6b00bcf389abd2ac4ffa675fb19eb4e1e5bdbd3f8bed9cda4b6c867258dc6, challenge: 04a29bf0c68be997c34ba5582033cadc266aaca43cb7c451d97c5a0bee9e7f70, plot_info: PlotInfo(prover=<chiapos.DiskProver object at 0x00000138164B6A70>, pool_public_key=None, pool_contract_puzzle_hash=<bytes32: 5316242367eb37f1ab1e982dfc26297a6392962cc0e423304881887cf6362447>, plot_public_key=<G1Element 80b82bde8eb21cb75b01d6eb203f078368ec09c1fe1763f0b0af0da730c09e8851f620ab1030a0c899ef6b2380362840>, file_size=76517452544, time_modified=1691015752.3365219)
2023-08-06T20:55:24.232 harvester chia.harvester.harvester: ERROR    Error using prover object connect() failed with: timeout (> 2000 ms)
2023-08-06T20:55:24.248 harvester chia.harvester.harvester: ERROR    File: F:\plot-k32-c8-2023-08-03-04-29-1b7781bdaf58b03eed3b16008a1530c28c7d676b14054746458293127374aae1.plot Plot ID: 1b7781bdaf58b03eed3b16008a1530c28c7d676b14054746458293127374aae1, challenge: fe8bd3f4208cda3cb2ce53da621d0b3204c0dd57cf0c63592f93e9429a103155, plot_info: PlotInfo(prover=<chiapos.DiskProver object at 0x00000138164B6AB0>, pool_public_key=None, pool_contract_puzzle_hash=<bytes32: 5316242367eb37f1ab1e982dfc26297a6392962cc0e423304881887cf6362447>, plot_public_key=<G1Element 89c3a5de567ed57992d1bc4a8107a123709fd890222c1f3291df2006a1a5408f8a67101c4da1fe6de8262f977bdbacb6>, file_size=76528740288, time_modified=1691026393.611205)
2023-08-06T20:57:26.797 harvester chia.harvester.harvester: ERROR    Error using prover object connect() failed with: timeout (> 2000 ms)
2023-08-06T20:57:26.812 harvester chia.harvester.harvester: ERROR    File: E:\plot-k32-c8-2023-08-02-09-07-1e484e16411c5535aaa8ae53e360de6ae4e5a2f086091b1f7ee6cc31f1b08421.plot Plot ID: 1e484e16411c5535aaa8ae53e360de6ae4e5a2f086091b1f7ee6cc31f1b08421, challenge: 4e4834e7c1e61a7b239314b3cc4ae94438c928cadbec36fc0a087ea9a15ae1d8, plot_info: PlotInfo(prover=<chiapos.DiskProver object at 0x000001381643FE70>, pool_public_key=None, pool_contract_puzzle_hash=<bytes32: 5316242367eb37f1ab1e982dfc26297a6392962cc0e423304881887cf6362447>, plot_public_key=<G1Element 8422b0c4c0830553f8d196f08b5795bf8d4179a9593aa8782b6fc7fab8da3a80d3814cb544c413a553b37f541932a3f1>, file_size=76552350256, time_modified=1690956664.9466884)

**Comment by zhurakovsky01** [comment]
What are your PC settings? Do you farm and build plots at the same time?

**Comment by Dakes12** [comment]
> What are your PC settings? Do you farm and build plots at the same time?

Hi,
I am not farming and plotting in the same time. I use this computer only for farming.  

What you mean by pc settings?

**Comment by zhurakovsky01** [comment]
> Что вы имеете в виду под настройками ПК?

Specifications of your PC?

**Comment by Dakes12** [comment]
> > Что вы имеете в виду под настройками ПК?
> 
> Specifications of your PC?

I have mentioned in the main post.

**Comment by Dakes12** [comment]
I have checked the plots, and compressed one seems to be invalid.

2023-08-12T16:58:40.076  chia.plotting.check_plots        : ERROR       Proofs 0 / 5, 0.0
2023-08-12T16:58:40.076  chia.plotting.check_plots        : INFO     Testing plot E:\plot-k32-c8-2023-08-12-16-43-e2fecc51cc67f4329a9e5f5a4dd3e68a81fa3cc8ccc6250040412d203c55d05e.plot k=32
2023-08-12T16:58:40.076  chia.plotting.check_plots        : INFO        Pool contract address:  xxxxx
2023-08-12T16:58:40.092  chia.plotting.check_plots        : INFO        Farmer public key:      xxxxx
2023-08-12T16:58:42.107  chia.plotting.check_plots        : ERROR    <class 'RuntimeError'>: connect() failed with: timeout (> 2000 ms) error in getting challenge qualities for plot E:\plot-k32-c8-2023-08-12-16-43-e2fecc51cc67f4329a9e5f5a4dd3e68a81fa3cc8ccc6250040412d203c55d05e.plot

Anyone know why?

**Comment by Dakes12** [comment]
Solved after setting up the plotting machine. 

Can someone help with remote compute?
I have started the remote compute server on the farmer.
On the harvester, i have added in system variables for the CHIAPOS_RECOMPUTE_HOST to farmer's ip. Nothing happens in the remote compute server. 
It shows:
[chiapos] Using 16 / 24 CPU threads
[chiapos] Using 1 / 1 CUDA devices
Using 16 / 24 CPU threads
Using NVIDIA GeForce RTX 3060 (CUDA (native))
ReComputeServer listening on 0.0.0.0 port 11989
