### ISSUE TITLE
[1.8.2.giga22] Farmer throws an exception when Harverter founds a proof

### ISSUE THREAD

**Issue by gbInArY** [madMAx43v3r/chia-gigahorse#223]
I get this error on the Farmer when the Harvester founds a _proof_. Tested on CPU farming.

Harvester:
`2023-10-23T23:44:52.257 harvester chia.harvester.harvester: INFO     Found proof: K = 32, C = 4, is_compressed = True, used_gpu = False, fee_rate = 1.5625 %`

Farmer:
`2023-10-23T23:44:52.268 farmer farmer_server              : ERROR    Exception: Value 317205378875758743471421320 does not fit into uint64, PeerInfo(_ip=IPv4Address('172.19.0.1'), _port=8448). Traceback (most recent call last):
  File "/opt/gigahorse/chia/server/ws_connection.py", line 398, in wrapped_coroutine
  File "/opt/gigahorse/chia/farmer/farmer_api.py", line 105, in new_proof_of_space
  File "/opt/gigahorse/chia/consensus/pot_iterations.py", line 61, in calculate_iterations_quality
  File "/opt/gigahorse/chia/util/struct_stream.py", line 69, in __init__
ValueError: Value 317205378875758743471421320 does not fit into uint64`

PD: It was working well with the previous stable version [1.8.2.giga14](https://github.com/madMAx43v3r/chia-gigahorse/releases/tag/v1.8.2.giga14)

**Comment by madMAx43v3r** [comment]
You probably are mixing different versions, need run the same version for Node + Farmer + Harvester.

Make sure to kill old versions with `chia stop all -d`.
