### ISSUE TITLE
RuntimeError: BlockStore does not support database schema v1

### ISSUE THREAD

**Issue by mbegunok** [madMAx43v3r/chia-gigahorse#232]
I upgrade to 2.1.1 Giga 23. And got an error when start farmer. Everyting forks in [1.8.2.giga22 Gigahorse 2.0 Node / Farmer].  Cuda plotter is running on background .Please help

Traceback (most recent call last):
  File "/home/max/Downloads/chia-gigahorse-farmer1/chia", line 7, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "/home/max/Downloads/chia-gigahorse-farmer1/chia_full_node", line 8, in <module multidist-2-chia_full_node>
  File "/home/max/Downloads/chia-gigahorse-farmer1/chia/server/start_full_node.py", line 121, in main
  File "/home/max/Downloads/chia-gigahorse-farmer1/chia/server/start_service.py", line 318, in async_run
  File "/home/max/Downloads/chia-gigahorse-farmer1/asyncio/runners.py", line 44, in run
  File "/home/max/Downloads/chia-gigahorse-farmer1/asyncio/base_events.py", line 616, in run_until_complete
  File "/home/max/Downloads/chia-gigahorse-farmer1/chia/server/start_full_node.py", line 104, in async_main
  File "/home/max/Downloads/chia-gigahorse-farmer1/chia/server/start_service.py", line 223, in run
  File "/home/max/Downloads/chia-gigahorse-farmer1/chia/server/start_service.py", line 182, in start
  File "/home/max/Downloads/chia-gigahorse-farmer1/chia/full_node/full_node.py", line 351, in _start
  File "/home/max/Downloads/chia-gigahorse-farmer1/chia/full_node/block_store.py", line 49, in create
RuntimeError: BlockStore does not support database schema v1

Also when I run farm summary
I receive following problem

Farming status: Not available
Total chia farmed: 22.501235595784
User transaction fees: 0.001235595784
Block rewards: 22.5
Last height farmed: 4471052
Local Harvester
   10796 plots of size: 730.531 TiB on-disk, 1.044 PiBe (effective)
Plot count for all harvesters: 10796
Total size of plots: 730.531 TiB, 1.044 PiBe (effective)
Estimated network space: Unknown
Expected time to win: Unknown
Note: log into your key using 'chia wallet show' to see rewards for each key

**Comment by madMAx43v3r** [comment]
You need to update to new DB v2, either sync from scratch or download from chia website.
