### ISSUE TITLE
Node doesn't seem to sync due to to many cpu cores/threads reported by zstd

### ISSUE THREAD

**Issue by xorinox** [madMAx43v3r/chia-gigahorse#24]
Hello, on a dual 64 core Epyc machine with a total of 255 CPU hyper threads, the zstd lib reports an error of bad thread count..  Below is running the gigahorse chia node. When I disable SMT, reducing the threads to 128 (via bios), then the nodes syncs fine. numactl/taskset only pin the process to CPU cores/threads but doesn't control how many threads zstd is seeing.

2023-02-24T00:05:02.563 full_node full_node_server        : ERROR    Exception: Bad threads count - more than 200: 255 <class 'zstd.Error'>, closing connection {'host': '193.72.52.204', 'port': 8444}. Traceback (most recent call last):
  File "/home/srv_chia/chia-gigahorse-farmer/chia/server/server.py", line 634, in api_call
  File "/home/srv_chia/chia-gigahorse-farmer/asyncio/tasks.py", line 494, in wait_for
  File "/home/srv_chia/chia-gigahorse-farmer/chia/server/server.py", line 624, in wrapped_coroutine
  File "/home/srv_chia/chia-gigahorse-farmer/chia/full_node/full_node_api.py", line 1495, in respond_compact_vdf
  File "/home/srv_chia/chia-gigahorse-farmer/chia/full_node/full_node.py", line 2512, in respond_compact_vdf
  File "/home/srv_chia/chia-gigahorse-farmer/chia/full_node/full_node.py", line 2413, in _replace_proof
  File "/home/srv_chia/chia-gigahorse-farmer/chia/full_node/block_store.py", line 174, in replace_proof
  File "/home/srv_chia/chia-gigahorse-farmer/chia/full_node/block_store.py", line 137, in compress
zstd.Error: Bad threads count - more than 200: 255

2023-02-24T00:05:02.701 full_node full_node_server        : WARNING  Banning 193.72.52.204 for 10 seconds
2023-02-24T00:05:02.701 full_node full_node_server        : INFO     Connection closed: 193.72.52.204, node id: 295ea99968c526f843ad70159c3c739ad8fc81374675a1523ed3e4f5a87436b3
2023-02-24T00:05:02.701 full_node chia.full_node.full_node: INFO     peer disconnected {'host': '193.72.52.204', 'port': 8444}
2023-02-24T00:05:02.702 full_node full_node_server        : WARNING  Banning 193.72.52.204 for 600 seconds
2023-02-24T00:05:02.703 full_node chia.full_node.full_node: ERROR    Error with syncing: <class 'RuntimeError'>Traceback (most recent call last):
  File "/home/srv_chia/chia-gigahorse-farmer/chia/full_node/full_node.py", line 1034, in _sync
RuntimeError: Weight proof did not arrive in time from peer: 193.72.52.204

**Comment by mwpastore** [comment]
https://github.com/sergey-dryabzhinsky/python-zstd/blob/d17f05b101d18b517fc3f1730b1a61e9faee3d46/src/python-zstd.c#L96

**Comment by mwpastore** [comment]
https://github.com/Chia-Network/chia-blockchain/issues/14667

**Comment by madMAx43v3r** [comment]
Ok try this fix: https://github.com/madMAx43v3r/chia-gigahorse/releases/download/v1.6.2.giga5/chia-gigahorse-farmer-1.6.2.giga5-fix1-x86_64.tar.gz

**Comment by xorinox** [comment]
Thank you guys!  This works like a breeze!  In no time node now synced up to max height.
