### ISSUE TITLE
Error starting Harvester

### ISSUE THREAD

**Issue by trxman** [madMAx43v3r/chia-gigahorse#262]
In Gentoo Linux environment, I get the following error after trying to start a farmer with remote compute configured (pointed to other host):

`2024-01-17T20:49:28.944 harvester chia.server.start_service: ERROR    fatal uncaught exception: TypeError: string indices must be integers
Traceback (most recent call last):
  File "/home/xxx/chia-gigahorse-farmer/chia/util/log_exceptions.py", line 20, in log_exceptions
  File "/home/xxx/chia-gigahorse-farmer/chia/server/start_service.py", line 321, in async_run
  File "/home/xxx/chia-gigahorse-farmer/asyncio/runners.py", line 44, in run
  File "/home/xxx/chia-gigahorse-farmer/asyncio/base_events.py", line 616, in run_until_complete
  File "/home/xxx/chia-gigahorse-farmer/chia/server/start_harvester.py", line 65, in async_main
  File "/home/xxx/chia-gigahorse-farmer/chia/util/config.py", line 348, in get_unresolved_peer_infos
  File "/home/xxx/chia-gigahorse-farmer/chia/util/config.py", line 348, in <setcontraction>
TypeError: string indices must be integers`

Afterwards, services are stuck/defunct.
I did 
`./chia.bin stop -d all`
and tried couple of times. :(

The same error pops up even after clearing
`unset CHIAPOS_RECOMPUTE_HOST`

Any suggestion?

**Comment by trxman** [comment]
I have tried 2.1.3.giga26 version, too, but I got the same error. :(

**Comment by trxman** [comment]
Ah... There was some error in config file. :(
It would be nice if this error message would mention something about failed reading of conf file. :)
