### ISSUE TITLE
2.3.0 giga36 fatal ERROR 

### ISSUE THREAD

**Issue by Ferz0id** [madMAx43v3r/chia-gigahorse#314]
2024-05-06T13:46:29.704 full_node chia.server.start_service: ERROR    fatal uncaught exception: ValueError: max_workers must be <= 61
Traceback (most recent call last):
  File "D:\soft\Crypto\Mining\Chia\chia-gigahorse-farmer\chia\util\log_exceptions.py", line 20, in log_exceptions
  File "D:\soft\Crypto\Mining\Chia\chia-gigahorse-farmer\chia\server\start_service.py", line 323, in async_run
  File "D:\soft\Crypto\Mining\Chia\chia-gigahorse-farmer\asyncio\runners.py", line 190, in run
  File "D:\soft\Crypto\Mining\Chia\chia-gigahorse-farmer\asyncio\runners.py", line 118, in run
  File "D:\soft\Crypto\Mining\Chia\chia-gigahorse-farmer\asyncio\base_events.py", line 653, in run_until_complete
  File "D:\soft\Crypto\Mining\Chia\chia-gigahorse-farmer\chia_full_node.py", line 85, in async_main
  File "D:\soft\Crypto\Mining\Chia\chia-gigahorse-farmer\chia\server\start_service.py", line 197, in run
  File "D:\soft\Crypto\Mining\Chia\chia-gigahorse-farmer\contextlib.py", line 204, in __aenter__
  File "D:\soft\Crypto\Mining\Chia\chia-gigahorse-farmer\chia\server\start_service.py", line 214, in manage
  File "D:\soft\Crypto\Mining\Chia\chia-gigahorse-farmer\contextlib.py", line 638, in enter_async_context
  File "D:\soft\Crypto\Mining\Chia\chia-gigahorse-farmer\contextlib.py", line 204, in __aenter__
  File "D:\soft\Crypto\Mining\Chia\chia-gigahorse-farmer\chia\full_node\full_node.py", line 266, in manage
  File "D:\soft\Crypto\Mining\Chia\chia-gigahorse-farmer\chia\consensus\blockchain.py", line 146, in create
  File "D:\soft\Crypto\Mining\Chia\chia-gigahorse-farmer\concurrent\futures\process.py", line 666, in __init__
ValueError: max_workers must be <= 61

Windows 11
2.3.0.giga36 Gigahorse 3.0 Node / Farmer

**Comment by madMAx43v3r** [comment]
Maybe some invalid value in config.yaml ?

**Comment by Ferz0id** [comment]
It's still the same, I have to use the old version (2.2.1). My system has two 64-core processors then mayby it's a bug point (max_workers must be <= 61)

**Comment by madMAx43v3r** [comment]
Yup it's a python limitation on windows. I'll limit it to 32 threads in next version, if Chia doesn't fix it themselves.

**Comment by madMAx43v3r** [comment]
They fixed it already: https://github.com/Chia-Network/chia-blockchain/pull/17958

**Comment by madMAx43v3r** [comment]
Actually you can set `full_node/reserved_cores` to `96` in your case to fix it in current version.
