### ISSUE TITLE
GH GUI Wallet not showing transactions after May 29th

### ISSUE THREAD

**Issue by spleen911** [madMAx43v3r/chia-gigahorse#323]
I noticed today that the GH GUI wallet does not show transactions after May 29th even though the node and wallet are synced. XCHScan shows the payouts from Space Pool.

My payout address has not changed. It has 516 transactions according to XCHScan.

Last block won in Farm stats also shows May 20th. I have won 2 blocks in June.

A series of these errors are repeating (different coin info) in the node log every 10 seconds.

```
2024-06-05T15:07:43.384 wallet chia.wallet.wallet_state_manager: ERROR    Failed to add coin_state: CoinState { coin: Coin { parent_coin_info: 3ff07eb358e8255a65c30a2dce0e5fbb00000000000000000000000000534ea9, puzzle_hash: 94e83105041d49dfea3024060dec8c4d4eedc849015fff7c74ea387ab25b9e2f, amount: 125200000000 }, spent_height: None, created_height: Some(5459629) }, error: unable to open database file
Traceback (most recent call last):
  File "T:\Chia\resources\app.asar.unpacked\daemon\chia\wallet\wallet_state_manager.py", line 1733, in _add_coin_states
  File "T:\Chia\resources\app.asar.unpacked\daemon\chia\wallet\wallet_state_manager.py", line 2222, in coin_added
  File "T:\Chia\resources\app.asar.unpacked\daemon\chia\wallet\wallet_coin_store.py", line 122, in add_coin_record
  File "T:\Chia\resources\app.asar.unpacked\daemon\aiosqlite\core.py", line 203, in execute_insert
  File "T:\Chia\resources\app.asar.unpacked\daemon\aiosqlite\core.py", line 132, in _execute
  File "T:\Chia\resources\app.asar.unpacked\daemon\aiosqlite\core.py", line 115, in run
  File "T:\Chia\resources\app.asar.unpacked\daemon\aiosqlite\core.py", line 88, in _execute_insert
sqlite3.OperationalError: unable to open database file

```

I stopped all services, backed up the wallet db, cleared the folder so it would create a new one, and the same errors repeat with the new wallet db file. I restored the original wallet db.

Yes, I am on windows, but no anti-virus scanning is in play. It isn't permissions. I haven't installed new patches since May 29th.

I launched 2.3.0 non-GH UI (wallet only) on a harvester and it has synced the wallet to current state. No wallet errors in that chia debug.log.

**Comment by spleen911** [comment]
I did the following and node's wallet is syncing again with no errors in debug log:

1. Close GH GUI, do not leave services running
2. Run **stop all -d** using CLI
3. Manually kill orphaned chia.exe processes (I had one)
4. Execute non-GH ChiaSetup-2.3.0.exe
5. Launch GH 2.3.0 using CLI
6. Launch non-GH GUI to verify node & wallet sync

Probably had nothing to do with GH at all.

If no wallet issues this week, I will re-run GH GUI install on top. I still use CLI **show** commands in parallel with GUI so it doesn't matter to me which GUI I actually use. It is nice you are providing a single setup with GH + GUI for simplicity. Thank you and keep up the awesome work.
