### ISSUE TITLE
Harvesting stopped

### ISSUE THREAD

**Issue by telix11** [madMAx43v3r/chia-gigahorse#335]
After successful harvesting chia-gigahorse 2.3.0 stopped working properly.
I get such error in the logfile and my spacefarmers pool stats showed 10 to-late partials and now shows nothing more.

2024-06-23T18:17:07.188 harvester harvester_server        : WARNING  Trying to ban localhost for 10, but will not ban
2024-06-23T18:27:10.237 harvester harvester_server        : ERROR    Exception:  <class 'asyncio.exceptions.TimeoutError'>, closing connection Pee
rInfo(_ip=IPv4Address('127.0.0.1'), _port=8447). Traceback (most recent call last):
  File "/home/mhorecki/chia-gigahorse230/chia/server/ws_connection.py", line 464, in _api_call
  File "/home/mhorecki/chia-gigahorse230/asyncio/tasks.py", line 501, in wait_for
asyncio.exceptions.TimeoutError

My GPU is working properly.

**Comment by madMAx43v3r** [comment]
Hard to say what the issue is given just this info... Does it work again if you restart it?

**Comment by madMAx43v3r** [comment]
Yes the plot filter halvening happened 10 days ago. What partial diff you using?

**Comment by telix11** [comment]
Some default settings. I did not change that parameter and I dont where to change it because I cant find it in the documentation.

**Comment by madMAx43v3r** [comment]
Then you can probably fix it by increasing partial diff, need to change on pool website settings. what pool you on?

**Comment by Kelcyo** [comment]
Where can I configure the partial difference increase in the Space Pool?

**Comment by madMAx43v3r** [comment]
![image](https://github.com/user-attachments/assets/47fbf470-7711-4c1b-8ad7-607eca8146a5)
