### ISSUE TITLE
Traceback (most recent call last)

### ISSUE THREAD

**Issue by gtx1070rig** [madMAx43v3r/chia-gigahorse#345]
Do i have a problem? (SOLO FARMING - Farming Space 1.848 PiBe - Total farm size raw 797.432 TiB - 1 local harvester, 1 remote harvester, max 8s. harvester latency)

2024-10-11T16:36:01.880 full_node aiohttp.server          : ERROR    Error handling request
Traceback (most recent call last):
  File "C:\PROGRA~1\Chia\RESOUR~1\APPASA~1.UNP\daemon\aiohttp\web_protocol.py", line 452, in _handle_request
  File "C:\PROGRA~1\Chia\RESOUR~1\APPASA~1.UNP\daemon\aiohttp\web_app.py", line 543, in _handle
  File "C:\PROGRA~1\Chia\RESOUR~1\APPASA~1.UNP\daemon\chia\server\server.py", line 309, in incoming_connection
  File "C:\PROGRA~1\Chia\RESOUR~1\APPASA~1.UNP\daemon\aiohttp\web_ws.py", line 152, in prepare
  File "C:\PROGRA~1\Chia\RESOUR~1\APPASA~1.UNP\daemon\aiohttp\web_response.py", line 417, in prepare
  File "C:\PROGRA~1\Chia\RESOUR~1\APPASA~1.UNP\daemon\aiohttp\web_response.py", line 425, in _start
  File "C:\PROGRA~1\Chia\RESOUR~1\APPASA~1.UNP\daemon\aiohttp\web_response.py", line 505, in _write_headers
  File "C:\PROGRA~1\Chia\RESOUR~1\APPASA~1.UNP\daemon\aiohttp\http_writer.py", line 130, in write_headers
  File "C:\PROGRA~1\Chia\RESOUR~1\APPASA~1.UNP\daemon\aiohttp\http_writer.py", line 75, in _write
ConnectionResetError: Cannot write to closing transport

**Comment by madMAx43v3r** [comment]
no just ignore
