### ISSUE TITLE
Harvesters with no GPUs

### ISSUE THREAD

**Issue by dietrichschmitz** [madMAx43v3r/chia-gigahorse#68]
Maybe I missed it elsewhere, but if you have a farmer using separate machines as harvesters (and running the Giga harvester on them), does the harvester need to have a GPU?  Running into the same error on two separate harvesters I've tried to set up.  This happens when I run start_harvester.  Farmer is otherwise fine and works wonderfully.

Traceback (most recent call last):
  File "C:\Users\Dietrich\Desktop\CHIA-G~1\chia.py", line 4, in <module>
  File "C:\Users\Dietrich\Desktop\CHIA-G~1\chia.py", line 12, in <module multidist-1-chia>
  File "C:\Users\Dietrich\Desktop\CHIA-G~1\chia\cmds\db.py", line 9, in <module chia.cmds.db>
  File "C:\Users\Dietrich\Desktop\CHIA-G~1\chia\cmds\db_validate_func.py", line 9, in <module chia.cmds.db_validate_func>
  File "C:\Users\Dietrich\Desktop\CHIA-G~1\chia\types\full_block.py", line 9, in <module chia.types.full_block>
  File "C:\Users\Dietrich\Desktop\CHIA-G~1\chia\types\blockchain_format\reward_chain_block.py", line 8, in <module chia.types.blockchain_format.reward_chain_block>
  File "C:\Users\Dietrich\Desktop\CHIA-G~1\chia\types\blockchain_format\proof_of_space.py", line 9, in <module chia.types.blockchain_format.proof_of_space>
ImportError: LoadLibraryExW 'C:\Users\Dietrich\Desktop\CHIA-G~1\chiapos.pyd' failed: The specified module could not be found.

**Comment by madMAx43v3r** [comment]
This error is not related to GPU, is that on windows? if yes, please install MSVC redistributable.

**Comment by madMAx43v3r** [comment]
> On Windows you might have to install latest Microsoft Visual C++ Redistributable: https://aka.ms/vs/17/release/vc_redist.x64.exe

**Comment by dietrichschmitz** [comment]
Yes  - it's Windows.  Two of my machines have the issue, and they are both an older model JBOD (Chenbro 12000NR).  My other computers don't seem to have the same issue.

Yes, did install that Microsoft Visual C++ Redistributable - and reinstalled it.  Still no success on the Chenbros.  I'll dig in further, and see what I can figure out.  Thanks for the info that it's not related to the GPU. :-)  Really appreciate your work on this tremendously.

**Comment by madMAx43v3r** [comment]
What CPU are these machines running?

**Comment by madMAx43v3r** [comment]
Hmm well, it could be a missing OpenCL library, can you trying installing the Intel version: https://www.intel.com/content/www/us/en/developer/tools/oneapi/base-toolkit-download.html

**Comment by madMAx43v3r** [comment]
Or Nvidia driver, doesnt matter

**Comment by Chiliheld** [comment]
since @dietrichschmitz did not report back... I've installed the OpenCL library and it worked on my Win10
