### ISSUE TITLE
getting too much errors on log file when using gigahorse

### ISSUE THREAD

**Issue by Lc001tr** [madMAx43v3r/chia-gigahorse#76]
2023-04-05T16:30:16.508 full_node full_node_server        : ERROR    Exception: bad bytes32 initializer b'\xc9\xb6\xa0\x7f\r\x94^\xf4\xe7T\x19\xa7\x92S\xccD3afs' <class 'ValueError'>, closing connection {'host': '171.7.99.35', 'port': 8449}. Traceback (most recent call last):
  File "C:\Users\CHIA-G~1\.\chia\server\server.py", line 617, in api_call
  File "C:\Users\CHIA-G~1\.\chia\util\api_decorators.py", line 60, in wrapper
  File "C:\Users\CHIA-G~1\.\chia\util\streamable.py", line 645, in from_bytes
  File "C:\Users\CHIA-G~1\.\chia\util\streamable.py", line 632, in parse
  File "C:\Users\CHIA-G~1\.\chia\util\streamable.py", line 440, in <lambda>
  File "C:\Users\CHIA-G~1\.\chia\util\streamable.py", line 391, in parse_list
  File "C:\Users\chia\util\byte_types.py", line 40, in parse
  File "C:\Users\chia\util\byte_types.py", line 35, in __init__
ValueError: bad bytes32 initializer b'\xc9\xb6\xa0\x7f\r\x94^\xf4\xe7T\x19\xa7\x92S\xccD3afs'

 File "C:\Users\.\chia\server\server.py", line 634, in api_call
RuntimeError: Task got bad yield: Message(type=44, id=None, data=b'\x00\x00\x03\xe8\x00\x00\x00\x0f124.120.126.238 \xfc\x00\x00\x00\x00d&\xd0h\x00\x00\x00\r76.133.90.171 \xfc\x00\x00\x00\x00d$\

**Comment by Lc001tr** [comment]
2023-04-05T17:58:56.344 full_node full_node_server        : ERROR    Exception: cannot reuse already awaited coroutine <class 'RuntimeError'>, closing connection {'host': '5.146.187.7', 'port': 8444}. Traceback (most recent call last):
  File \chia\server\server.py", line 634, in api_call
RuntimeError: cannot reuse already awaited coroutine

**Comment by madMAx43v3r** [comment]
You cannot mix Gigahorse Farmer / Harvester with an official Chia Node, need to use Gigahorse Node as well.

**Comment by Lc001tr** [comment]
But in readme you wrote that if we use same version, (1.6.2) we can open chia node after starting gigahorse node.

**Comment by madMAx43v3r** [comment]
Yes, in that case only the GUI is running from official sources. But need to make sure to do it properly, stop all official stuff first via `chia stop all -d` or close the GUI.

**Comment by Lc001tr** [comment]
Interesing, I use Win-10.
I start gigahorse start_farmer.cmd
then I double click on desktop icon. these faults happen because some original chia services runs in background in paralel to gigahorse. But everything seems working I can get rewards from pool. 
When I close GUI everything stops.
For now when I start Chia.exe (gui executable) from powershell and close it from powershell I can exit GUI without stopping all. couldn't figure out how to start/stop gui without stopping or starting services.
So maybe you can compile the GUI in your next version for noobs like us.
