### ISSUE TITLE
Start error windows version gigahorse

### ISSUE THREAD

**Issue by wangyi-pool** [madMAx43v3r/chia-gigahorse#82]
PS C:\Users\CHIA_GPU\Desktop\chia-gigahorse-farmer> .\chia.exe show s
Traceback (most recent call last):
  File "C:\Users\CHIA_GPU\Desktop\CHIA-G~1\chia.py", line 4, in <module>
  File "C:\Users\CHIA_GPU\Desktop\CHIA-G~1\chia.py", line 9, in <module multidist-1-chia>
  File "C:\Users\CHIA_GPU\Desktop\CHIA-G~1\chia\cmds\beta.py", line 10, in <module chia.cmds.beta>
  File "C:\Users\CHIA_GPU\Desktop\CHIA-G~1\chia\cmds\beta_funcs.py", line 9, in <module chia.cmds.beta_funcs>
  File "C:\Users\CHIA_GPU\Desktop\CHIA-G~1\chia\util\chia_logging.py", line 11, in <module chia.util.chia_logging>
  File "C:\Users\CHIA_GPU\Desktop\CHIA-G~1\chia\cmds\init_funcs.py", line 13, in <module chia.cmds.init_funcs>
  File "C:\Users\CHIA_GPU\Desktop\CHIA-G~1\chia\consensus\coinbase.py", line 3, in <module chia.consensus.coinbase>
ImportError

What is the solution to this error？

**Comment by madMAx43v3r** [comment]
I think, you need to have a OpenCL driver installed, either AMD / NVidia or Intel driver.

**Comment by madMAx43v3r** [comment]
For example, Intel's driver package: https://registrationcenter-download.intel.com/akdlm/IRC_NAS/17207/intel_sdk_for_opencl_applications_2020.3.494.zip

**Comment by wangyi-pool** [comment]
The problem has not been resolved.

**Comment by madMAx43v3r** [comment]
You might also have to install latest Microsoft Visual C++ Redistributable: https://aka.ms/vs/17/release/vc_redist.x64.exe

**Comment by wangyi-pool** [comment]
Solved it,Thanks a million.
