### ISSUE TITLE
ValueError: wallet: already running

### ISSUE THREAD

**Issue by fantasyfanwuren** [madMAx43v3r/chia-gigahorse#85]
fanwuren@fanwuren-desktop:~/桌面/chia-gigahorse-farmer$ ./chia.bin stop all -d
chia_harvester: Stopped
chia_farmer: Stopped
chia_full_node: Stopped
chia_wallet: Stopped
Daemon stopped
fanwuren@fanwuren-desktop:~/桌面/chia-gigahorse-farmer$ ./chia.bin start farmer
Daemon not started yet
Starting daemon
(Unlock Keyring) Passphrase: 
Unlocking daemon keyring
chia_harvester: started
chia_farmer: started
chia_full_node: started
chia_wallet: started
fanwuren@fanwuren-desktop:~/桌面/chia-gigahorse-farmer$ Traceback (most recent call last):
  File "/home/fanwuren/桌面/chia-gigahorse-farmer/chia/util/lock.py", line 42, in acquire
  File "/home/fanwuren/桌面/chia-gigahorse-farmer/filelock/_api.py", line 183, in acquire
filelock._error.Timeout: The file lock '/home/fanwuren/.chia/mainnet/run/wallet.lock' could not be acquired.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/fanwuren/桌面/chia-gigahorse-farmer/chia/server/start_service.py", line 184, in run
  File "/home/fanwuren/桌面/chia-gigahorse-farmer/chia/util/lock.py", line 29, in __enter__
  File "/home/fanwuren/桌面/chia-gigahorse-farmer/chia/util/lock.py", line 44, in acquire
chia.util.lock.LockfileError: The file lock '/home/fanwuren/.chia/mainnet/run/wallet.lock' could not be acquired.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/fanwuren/桌面/chia-gigahorse-farmer/chia", line 16, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "/home/fanwuren/桌面/chia-gigahorse-farmer/chia_wallet", line 8, in <module multidist-5-chia_wallet>
  File "/home/fanwuren/桌面/chia-gigahorse-farmer/chia/server/start_wallet.py", line 116, in main
  File "/home/fanwuren/桌面/chia-gigahorse-farmer/chia/server/start_service.py", line 286, in async_run
  File "/home/fanwuren/桌面/chia-gigahorse-farmer/asyncio/runners.py", line 44, in run
  File "/home/fanwuren/桌面/chia-gigahorse-farmer/asyncio/base_events.py", line 616, in run_until_complete
  File "/home/fanwuren/桌面/chia-gigahorse-farmer/chia/server/start_wallet.py", line 107, in async_main
  File "/home/fanwuren/桌面/chia-gigahorse-farmer/chia/server/start_service.py", line 189, in run
ValueError: wallet: already running

**Comment by madMAx43v3r** [comment]
Can you try rebooting the machine?

**Comment by madMAx43v3r** [comment]
And then delete `/home/fanwuren/.chia/mainnet/run/wallet.lock`
