### ISSUE TITLE
Problem connecting harvester to farmer

### ISSUE THREAD

**Issue by thinkboxx** [madMAx43v3r/chia-gigahorse#93]
I have a problem connecting harvester to farmer.
On the harvester I'm getting an error

2023-04-26T02:21:24.895 harvester harvester               : INFO     Reconnecting to peer {'host': '192.168.1.250', 'port': 8447}
2023-04-26T02:21:24.897 harvester harvester_server        : DEBUG    Connecting: wss://192.168.1.250:8447/ws, Peer info: {'host': '192.168.1.250', 'port': 8447}
2023-04-26T02:21:24.911 harvester harvester_server        : DEBUG    -> handshake to peer 192.168.1.250 c0161ed4da50db05cfc9021c2179ee48012f502d3c09141f0cd2a23422e233c2
2023-04-26T02:21:24.912 harvester harvester_server        : INFO     Connected with farmer {'host': '192.168.1.250', 'port': 8447}
2023-04-26T02:21:24.914 harvester harvester_server        : DEBUG    <- harvester_handshake from peer c0161ed4da50db05cfc9021c2179ee48012f502d3c09141f0cd2a23422e233c2 192.168.1.250
2023-04-26T02:21:24.915 harvester harvester_server        : ERROR    Exception: Given G1 non-infinity element must start with 0b10 <class 'ValueError'>, closing connection {'host': '192.168.1.250', 'port': 8447}. Traceback (most recent call last):
  File "/home/thinkboxx/chia-blockchain/chia/server/server.py", line 599, in api_call
    coroutine = f(full_message.data, connection)
  File "/home/thinkboxx/chia-blockchain/chia/util/api_decorators.py", line 33, in f_substitute
    inter[param_name] = param_class.from_bytes(inter[param_name])
  File "/home/thinkboxx/chia-blockchain/chia/util/streamable.py", line 521, in from_bytes
    parsed = cls.parse(f)
  File "/home/thinkboxx/chia-blockchain/chia/util/streamable.py", line 463, in parse
    for field, value in zip(fields, values):
  File "/home/thinkboxx/chia-blockchain/chia/util/streamable.py", line 462, in <genexpr>
    values: Iterator[object] = (parse_f(f) for parse_f in PARSE_FUNCTIONS_FOR_STREAMABLE_CLASS[cls])
  File "/home/thinkboxx/chia-blockchain/chia/util/streamable.py", line 442, in <lambda>
    return lambda f: parse_list(f, parse_inner_type_f)
  File "/home/thinkboxx/chia-blockchain/chia/util/streamable.py", line 193, in parse_list
    full_list.append(parse_inner_type_f(f))
  File "/home/thinkboxx/chia-blockchain/chia/util/streamable.py", line 449, in <lambda>
    return lambda f: parse_size_hints(f, f_type, bytes_to_read, unchecked=True)
  File "/home/thinkboxx/chia-blockchain/chia/util/streamable.py", line 208, in parse_size_hints
    return f_type.from_bytes_unchecked(bytes_read)
ValueError: Given G1 non-infinity element must start with 0b10

2023-04-26T02:21:24.915 harvester harvester_server        : DEBUG    Inbound_handler task cancelled
2023-04-26T02:21:24.916 harvester harvester_server        : INFO     Connection closed: 192.168.1.250, node id: c0161ed4da50db05cfc9021c2179ee48012f502d3c09141f0cd2a23422e233c2
2023-04-26T02:21:24.917 harvester harvester_server        : WARNING  Banning 192.168.1.250 for 10 seconds

both harvester and the farmer are the latest vesion.

thinkboxx@chia11:~$ /home/thinkboxx/chia-gigahorse-farmer/chia.bin version
1.7.1.giga9

C:\x\chia-gigahorse-farmer>chia.exe version
1.7.1.giga9

I have other harvesters connected to this farmer.
I tried chia init, fresh config, nothing is working.

Please help.
Thank you

**Comment by thinkboxx** [comment]
I figured it out.
My issue was I was only retarting the harvester and forgot to restart the daemon.
