### ISSUE TITLE
Could not farm anymore 

### ISSUE THREAD

**Issue by itprojekte** [madMAx43v3r/chia-gigahorse#95]
Hi Mad, 

my farmer is down from today i got some issue or error message: 
2023-04-26T16:52:55.775 farmer chia.farmer.farmer         : ERROR    Could not find authentication sk for 6e8878978a906566b816795b0e8813976024e25d4783e39984e390ca1f430bfa

can you help here.. Thank

**Comment by madMAx43v3r** [comment]
restart doesn't work?

**Comment by itprojekte** [comment]
hi.. yes i do but it does not work.. i try all the version 1.6.2 and the new one 1.7.1 both not work anymore.. any ideas?

**Comment by itprojekte** [comment]
Here more  error message: 
2023-04-27T23:50:51.275 full_node full_node_server        : ERROR    Exception: Failed to fetch block 3583086 from {'host': '83.151.206.122', 'port': 8444}, timed out <class 'ValueError'>, closing connection {'host': '83.151.206.122', 'port': 8444}. Traceback (most recent call last):
  File "C:\MadMax\CHIA-G~1.2\.\chia\server\server.py", line 634, in api_call
  File "C:\MadMax\CHIA-G~1.2\.\asyncio\tasks.py", line 408, in wait_for
  File "C:\MadMax\CHIA-G~1.2\.\chia\server\server.py", line 624, in wrapped_coroutine
  File "C:\MadMax\CHIA-G~1.2\.\chia\full_node\full_node_api.py", line 131, in new_peak
  File "C:\MadMax\CHIA-G~1.2\.\chia\full_node\full_node.py", line 729, in new_peak
  File "C:\MadMax\CHIA-G~1.2\.\chia\full_node\full_node.py", line 649, in short_sync_backtrack
ValueError: Failed to fetch block 3583086 from {'host': '83.151.206.122', 'port': 8444}, timed out

2023-04-27T23:50:51.275 full_node full_node_server        : WARNING  Banning 83.151.206.122 for 10 seconds
2023-04-27T23:50:53.009 farmer chia.farmer.farmer         : ERROR    Could not find authentication sk for 6e8878978a906566b816795b0e8813976024e25d4783e39984e390ca1f430bfa

**Comment by madMAx43v3r** [comment]
try to rename `config.yaml` to `config.yaml.old` and run `chia.bin init`, then update the new config file with the settings you need

**Comment by itprojekte** [comment]
ok i do what you explain i use the version 1.7.1 from chia and also from gigahorse now i get is error message: 
2023-04-28T23:23:28.267 wallet chia.rpc.rpc_server        : WARNING  Error while handling message: Traceback (most recent call last):
  File "chia\rpc\rpc_server.py", line 340, in safe_handle
  File "chia\rpc\rpc_server.py", line 331, in ws_api
  File "chia\rpc\wallet_rpc_api.py", line 1243, in get_notifications
  File "chia\wallet\wallet_node.py", line 153, in wallet_state_manager
RuntimeError: wallet state manager not assigned

2023-04-28T23:23:28.269 wallet chia.rpc.rpc_server        : WARNING  Error while handling message: Traceback (most recent call last):
  File "chia\rpc\rpc_server.py", line 340, in safe_handle
  File "chia\rpc\rpc_server.py", line 331, in ws_api
  File "chia\rpc\wallet_rpc_api.py", line 519, in get_sync_status
  File "chia\wallet\wallet_node.py", line 153, in wallet_state_manager
RuntimeError: wallet state manager not assigned

2023-04-28T23:23:28.271 wallet chia.rpc.rpc_server        : WARNING  Error while handling message: Traceback (most recent call last):
  File "chia\rpc\rpc_server.py", line 340, in safe_handle
  File "chia\rpc\rpc_server.py", line 331, in ws_api
  File "chia\rpc\wallet_rpc_api.py", line 579, in get_wallets
  File "chia\wallet\wallet_node.py", line 153, in wallet_state_manager
RuntimeError: wallet state manager not assigned

2023-04-28T23:23:29.072 wallet wallet_server              : ERROR    Caught Exception: wallet state manager not assigned. Traceback: Traceback (most recent call last):
  File "chia\util\log_exceptions.py", line 11, in log_exceptions
  File "chia\server\ws_connection.py", line 306, in close
  File "chia\server\server.py", line 540, in connection_closed
  File "chia\wallet\wallet_node.py", line 654, in on_disconnect
  File "chia\wallet\wallet_node.py", line 153, in wallet_state_manager
RuntimeError: wallet state manager not assigned

2023-04-28T23:23:36.376 wallet wallet_server              : ERROR    Caught Exception: wallet state manager not assigned. Traceback: Traceback (most recent call last):
  File "chia\util\log_exceptions.py", line 11, in log_exceptions
  File "chia\server\ws_connection.py", line 306, in close
  File "chia\server\server.py", line 540, in connection_closed
  File "chia\wallet\wallet_node.py", line 654, in on_disconnect
  File "chia\wallet\wallet_node.py", line 153, in wallet_state_manager
RuntimeError: wallet state manager not assigned

2023-04-28T23:23:36.879 harvester chia.plotting.cache     : ERROR    Failed to load cache: DiskProver: Invalid version., Traceback (most recent call last):
  File "chia\plotting\cache.py", line 143, in load
ValueError: DiskProver: Invalid version.

2023-04-28T23:23:37.029 harvester chia.plotting.manager   : ERROR    Failed to open file C:\HDD\DS-FARM147\plot-k32-c7-2023-03-14-14-12-7d76e6af31014983ca75f5f067ce42530f55877c7dabd90448b528127c937630.plot. Invalid plot file format Traceback (most recent call last):
  File "chia\plotting\manager.py", line 274, in process_file
ValueError: Invalid plot file format
2023-04-28T23:23:38.362 wallet chia.rpc.rpc_server        : WARNING  Error while handling message: Traceback (most recent call last):
  File "chia\rpc\rpc_server.py", line 340, in safe_handle
  File "chia\rpc\rpc_server.py", line 331, in ws_api
  File "chia\rpc\wallet_rpc_api.py", line 519, in get_sync_status
  File "chia\wallet\wallet_node.py", line 153, in wallet_state_manager
RuntimeError: wallet state manager not assigned

2023-04-28T23:23:43.203 wallet wallet_server              : ERROR    Caught Exception: wallet state manager not assigned. Traceback: Traceback (most recent call last):
  File "chia\util\log_exceptions.py", line 11, in log_exceptions
  File "chia\server\ws_connection.py", line 306, in close
  File "chia\server\server.py", line 540, in connection_closed
  File "chia\wallet\wallet_node.py", line 654, in on_disconnect
  File "chia\wallet\wallet_node.py", line 153, in wallet_state_manager
RuntimeError: wallet state manager not assigned

2023-04-28T23:23:43.508 wallet wallet_server              : ERROR    Caught Exception: wallet state manager not assigned. Traceback: Traceback (most recent call last):
  File "chia\util\log_exceptions.py", line 11, in log_exceptions
  File "chia\server\ws_connection.py", line 306, in close
  File "chia\server\server.py", line 540, in connection_closed
  File "chia\wallet\wallet_node.py", line 654, in on_disconnect
  File "chia\wallet\wallet_node.py", line 153, in wallet_state_manager
RuntimeError: wallet state manager not assigned

2023-04-28T23:23:43.566 wallet wallet_server              : ERROR    Caught Exception: wallet state manager not assigned. Traceback: Traceback (most recent call last):
  File "chia\util\log_exceptions.py", line 11, in log_exceptions
  File "chia\server\ws_connection.py", line 306, in close
  File "chia\server\server.py", line 540, in connection_closed
  File "chia\wallet\wallet_node.py", line 654, in on_disconnect
  File "chia\wallet\wallet_node.py", line 153, in wallet_state_manager
RuntimeError: wallet state manager not assigned

2023-04-28T23:23:43.569 wallet wallet_server              : ERROR    Caught Exception: wallet state manager not assigned. Traceback: Traceback (most recent call last):
  File "chia\util\log_exceptions.py", line 11, in log_exceptions
  File "chia\server\ws_connection.py", line 306, in close
  File "chia\server\server.py", line 540, in connection_closed
  File "chia\wallet\wallet_node.py", line 654, in on_disconnect
  File "chia\wallet\wallet_node.py", line 153, in wallet_state_manager
RuntimeError: wallet state manager not assigned

2023-04-28T23:24:40.076 farmer chia.farmer.farmer         : ERROR    Could not find authentication sk for 6e8878978a906566b816795b0e8813976024e25d4783e39984e390ca1f430bfa
2023-04-28T23:25:19.103 farmer chia.farmer.farmer         : ERROR    Could not find authentication sk for 6e8878978a906566b816795b0e8813976024e25d4783e39984e390ca1f430bfa

i hope you can help me ;-)

**Comment by madMAx43v3r** [comment]
> 2023-04-28T23:23:36.879 harvester chia.plotting.cache : ERROR Failed to load cache: DiskProver: Invalid version., Traceback (most recent call last):

Gigahorse does not use the plot cache, so you are not running Gigahorse here...

**Comment by itprojekte** [comment]
i try everythink delete the config and renew it.. now the only issue the i bcame is: 
2023-04-30T00:10:53.260 farmer chia.farmer.farmer         : ERROR    Could not find authentication sk for 6e8878978a906566b816795b0e8813976024e25d4783e39984e390ca1f430bfa

I dont know with authentication is meaning here.. 

i use the flexpool.io for plots is that problem? 

Thanks for help ;-)

**Comment by itprojekte** [comment]
2023-04-30T00:22:15.853 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2023-04-30T00:22:15.853 wallet wallet_server              : WARNING  Banning 89.173.22.235 for 120 seconds
2023-04-30T00:22:15.853 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2023-04-30T00:22:15.869 wallet wallet_server              : WARNING  Banning 181.228.248.50 for 120 seconds
2023-04-30T00:22:15.869 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2023-04-30T00:22:15.869 wallet wallet_server              : WARNING  Banning 89.173.22.235 for 120 seconds
2023-04-30T00:22:15.869 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2023-04-30T00:22:15.869 wallet wallet_server              : WARNING  Banning 181.228.248.50 for 120 seconds
2023-04-30T00:22:15.884 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2023-04-30T00:22:15.884 wallet wallet_server              : WARNING  Banning 181.228.248.50 for 120 seconds
2023-04-30T00:22:15.884 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2023-04-30T00:22:15.884 wallet wallet_server              : WARNING  Banning 89.173.22.235 for 120 seconds
2023-04-30T00:22:15.884 wallet chia.wallet.wallet_node    : WARNING  Peer None did not respond in time.
2023-04-30T00:22:15.884 wallet wallet_server              : WARNING  Banning 89.173.22.235 for 120 seconds

What are this errors meaning?

**Comment by madMAx43v3r** [comment]
See here: https://github.com/Chia-Network/chia-blockchain/issues/9245

>  2023-04-30T00:22:15.884 wallet chia.wallet.wallet_node : WARNING Peer None did not respond in time.

That's normal.
